show databases;

CREATE DATABASE RESERVATION;

USE reservation;
show tables;
CREATE TABLE USER(
ID INT NOT NULL auto_increment,
FIRSTNAME varchar(20),
LASTNAME varchar(20),
EMAIL varchar(20),
PASSWORD varchar(20),
primary key(ID),
unique key(EMAIL)
);

CREATE TABLE FLIGHT(
ID INT NOT NULL auto_increment,
FLIGHT_NUMBER varchar(20) NOT NULL,
OPERATING_AIRLINES varchar(20) NOT NULL,
DEPARTURE_CITY varchar(20) NOT NULL,
ARRIVAL_CITY varchar(20) NOT NULL,
DATE_OF_DEPARTURE DATE NOT NULL,
ESTIMATED_DEPARTURE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
primary key(ID)
);

CREATE TABLE PASSENGER(
ID INT NOT NULL auto_increment,
FIRST_NAME varchar(256),
LAST_NAME varchar(256),
MIDDLE_NAME varchar(256),
EMAIL varchar(50),
PHONE varchar(10),
primary key(ID)
);

CREATE TABLE RESERVATION
(
ID INT NOT NULL auto_increment,
CHECKED_IN TINYINT(1),
NUMBER_OF_BAGS INT,
PASSENGER_ID INT,
FLIGHT_ID INT,
CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID),
FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(ID) ON DELETE CASCADE,
FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(ID)
);

SELECT * FROM USER ;
SELECT * FROM PASSENGER;
SELECT * FROM FLIGHT;
SELECT * FROM RESERVATION;


#DROP TABLE USER;
#DROP TABLE PASSENGER;
#DROP TABLE FLIGHT;
#DROP TABLE RESERVATION;
insert into passenger values(1,'navin','American','AUS',
'n5556@gm.com','988755875');

delete from passenger where id=17;
delete from flight where id=1;
DROP DATABASE RESERVATION;
ALTER TABLE PASSENGER DROP COLUMN middlename;
